### ISSUE TITLE
1.0.0 release checklist

### ISSUE THREAD

**Issue by ldilley** [FragLand/terracord#22]
- [x] Ensure Terracord still reconnects to Discord after a disconnect without `Task.Delay(-1)` in `BotConnect()` (related to #25)
- [x] Categorize and close any remaining issues associated with this release
- [x] Set plugin version to `1.0.0` in `Terracord.cs` and `Terracord.csproj`
- [x] Update copyright year as a range to include 2020 in `Terracord.cs` and `Terracord.csproj`
- [x] Create `1.0.0` tag
- [x] Create and publish release zip archive containing a `readme.txt` with installation instructions, a default `terracord.xml` configuration file, and all necessary DLLs accompanied by any relevant 3rd-party licenses
