### ISSUE TITLE
1.1.0 release checklist

### ISSUE THREAD

**Issue by ldilley** [FragLand/terracord#43]
- [x] Categorize and close any remaining issues associated with this release
- [x] Set plugin version to `1.1.0` in `Terracord.cs` and `Terracord.csproj`
- [x] Any bug fixes will increment the patch level beyond `1.1.0` at this point (`1.1.1` for example)
- [x] Create `1.1.0` tag (and any further tags to accommodate bug fix releases)
- [x] Create and publish release zip archive containing a `readme.txt` with installation instructions, a default `terracord.xml` configuration file, and all necessary DLLs (including localization resources) accompanied by any relevant 3rd-party licenses

**Comment by ldilley** [comment]
Temporarily freezing further feature updates to the master branch for a couple of days to allow more testing before tagging the `1.1.0` release. Any bug fixes will increment the patch number at this point (`1.1.1` for example).
