### ISSUE TITLE
1.2.0 release checklist

### ISSUE THREAD

**Issue by ldilley** [FragLand/terracord#62]
- [x] Categorize and close any remaining issues associated with this release
- [x] Set plugin version to `1.2.0` in `Terracord.cs` and `Terracord.csproj`
- [x] Add support for Terraria 1.4.x/TShock 4.4.x (#70)
- [x] Create `1.2.0` tag
- [x] Create and publish release zip archive containing a `readme.txt` with installation instructions, a default `terracord.xml` configuration file, and all necessary DLLs (including localization resources) accompanied by any relevant 3rd-party licenses
