### ISSUE TITLE
1.2.1 release checklist

### ISSUE THREAD

**Issue by ldilley** [FragLand/terracord#84]
- [x] Categorize and close any remaining issues associated with this release
- [x] Set plugin version to `1.2.1` in `Terracord.cs` and `Terracord.csproj`
- [x] Ensure plugin is fully compatible with latest TShock release (preferably **stable** 4.4.x)
- [x] Create `1.2.1` tag
- [x] Create and publish release zip archive containing a `readme.txt` with installation instructions, a default `terracord.xml` configuration file, and all necessary DLLs (including localization resources) accompanied by any relevant 3rd-party licenses
- [x] Add reference to @Dids' Docker image (https://github.com/Didstopia/terraria-server) in `readme.txt`
